-- Add alpaca bloodline percent columns to Animals table
-- Run once in SQL Server Management Studio

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Animals' AND COLUMN_NAME = 'PercentPeruvian')
    ALTER TABLE Animals ADD PercentPeruvian NVARCHAR(50) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Animals' AND COLUMN_NAME = 'PercentChilean')
    ALTER TABLE Animals ADD PercentChilean NVARCHAR(50) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Animals' AND COLUMN_NAME = 'PercentBolivian')
    ALTER TABLE Animals ADD PercentBolivian NVARCHAR(50) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Animals' AND COLUMN_NAME = 'PercentUnknownOther')
    ALTER TABLE Animals ADD PercentUnknownOther NVARCHAR(50) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Animals' AND COLUMN_NAME = 'PercentAccoyo')
    ALTER TABLE Animals ADD PercentAccoyo NVARCHAR(50) NULL;
