IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'HerdHealthReproduction')
CREATE TABLE HerdHealthReproduction (
    ReproductionID       INT IDENTITY(1,1) PRIMARY KEY,
    BusinessID           INT NOT NULL,
    AnimalTag            VARCHAR(100),
    Species              VARCHAR(100),
    EventType            VARCHAR(100),
    EventDate            DATE,
    BreedingMethod       VARCHAR(100),
    SireTag              VARCHAR(100),
    SireName             VARCHAR(200),
    SireBreed            VARCHAR(100),
    SireRegNumber        VARCHAR(100),
    PregnancyStatus      VARCHAR(50),
    PregnancyCheckDate   DATE,
    PregnancyCheckMethod VARCHAR(100),
    ExpectedDueDate      DATE,
    ActualBirthDate      DATE,
    NumberBorn           INT,
    NumberBornAlive      INT,
    BirthWeightLbs       DECIMAL(8,2),
    BirthEase            VARCHAR(100),
    OffspringTags        VARCHAR(500),
    WeanDate             DATE,
    WeanWeightLbs        DECIMAL(8,2),
    PerformedBy          VARCHAR(200),
    Notes                NVARCHAR(MAX),
    CreatedAt            DATETIME DEFAULT GETUTCDATE(),
    UpdatedAt            DATETIME DEFAULT GETUTCDATE()
);
