steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'oatsense/Dockerfile.backend'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/oatmeal-farm-registry/oatsense:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/oatmeal-farm-registry/oatsense:latest'

images:
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/oatmeal-farm-registry/oatsense:latest'
