"""
Data contract (Firestore message schema).
"""
from pydantic import BaseModel, Field, ConfigDict
from typing import List, Optional, Literal
from datetime import datetime

class MessageMetadata(BaseModel):
    """Metadata attached to message
       Extendable for analytics, moderation, routing, etc."""
    advisory_type: Optional[str] = Field(
        default=None,
        description="category of advisory (e.g., crops, livestock, weather)."
    )
    model_config = ConfigDict(extra = "allow")
    # Allows future metadata fields without breaking validation
   
class MessageModel(BaseModel):
    """
    Firestore message document schemd. 
    This acts as the single source of truth (data contract)
    betweeen backend, UI, and long-term memory systems.

    """
    
    # core identifiers
    thread_id: str = Field(
        ...,
        description="Unique identifier for the conversation thread."

    )

    user_id: str = Field(
        ...,
        description="Identifier for the user participating in the conversation."
    )

    # message content
    role: Literal["user", "assistant","system"] = Field(
        ...,
        description="Role of the message sender, either 'user' or 'assistant'."
    )

    content: str = Field(
        ...,
        min_length=1,
        description="The text content of the message."
    )

    # optional structured reccomendations (used in advisory flows)
    recommendations: Optional[List[dict]] = Field(
        default=None,
        description="List of actionable recommendations generated by assitant"
    )

    # message metadata
    metadata: Optional[MessageMetadata] = Field(
        default=None,
        description="Structured metadata associated with the message"
    )

    # Status tracking
    status: Literal["pending", "complete", "failed"] = Field(
        default="complete",
        description="Processing state of the message."
    )

    # Timestamps
    timestamp: datetime = Field(
        ...,
        description="Original message creation time (ISO 8601 format)."
    )

    updated_at: Optional[datetime] = Field(
        default=None,
        description="Last updated timestamp (Firestore server timestamp)."
    )

    model_config = ConfigDict(
        populate_by_name=True,
        str_strip_whitespace=True,
        validate_assignment=True,
        extra="forbid"  # Prevent unexpected fields at root level
    )


# Compat alias used by older call sites / docs
MessageContract = MessageModel
