"""
Event lead retrieval — exhibitor scans an attendee badge to capture a lead.

Flow:
  1. Exhibitor (vendor with an approved booth) opens the lead-capture page
     scoped to their booth's BusinessID.
  2. They enter / scan a BadgeCode (the same code generated by the conference
     check-in flow). The endpoint resolves it to a Registration row.
  3. They add notes / a 1-5 star rating / follow-up status. Saved as a scan.
  4. Later, they download all their leads as CSV for CRM import.

Access: writes are scoped to the scanning person's BusinessID — they can only
add scans for booths they own. Reads are likewise scoped to the requesting
business so exhibitors can't see each other's leads.
"""
import csv, io
from datetime import datetime
from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from sqlalchemy import text
from typing import Optional
from app.database import get_db, SessionLocal

router = APIRouter()


def ensure_tables(db: Session):
    db.execute(text("""
        IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'OFNEventLeadScan')
        CREATE TABLE OFNEventLeadScan (
            ScanID            INT IDENTITY(1,1) PRIMARY KEY,
            EventID           INT NOT NULL,
            ExhibitorBusinessID INT NOT NULL,
            BoothAppID        INT NULL,                -- optional link to vendor app
            ScannedByPeopleID INT NOT NULL,
            -- Attendee identification — at least one of these populated
            AttendeeRegID     INT NULL,                -- conference registration ID
            AttendeeName      NVARCHAR(300),
            AttendeeEmail     NVARCHAR(300),
            AttendeePhone     NVARCHAR(50),
            AttendeeBusiness  NVARCHAR(300),
            BadgeCode         NVARCHAR(80),
            -- Lead-quality fields
            Rating            INT NULL,                -- 1..5 stars
            Interest          NVARCHAR(500),           -- product interest tag
            Notes             NVARCHAR(MAX),
            FollowUpStatus    NVARCHAR(50) DEFAULT 'new', -- new / contacted / qualified / lost / won
            FollowUpAt        DATETIME NULL,
            ScanDate          DATETIME DEFAULT GETDATE(),
            UpdatedDate       DATETIME DEFAULT GETDATE()
        )
    """))
    db.execute(text("""
        IF NOT EXISTS (SELECT 1 FROM sys.indexes
                        WHERE name='IX_OFNEventLeadScan_Exhibitor'
                          AND object_id = OBJECT_ID('OFNEventLeadScan'))
        CREATE INDEX IX_OFNEventLeadScan_Exhibitor
                  ON OFNEventLeadScan (EventID, ExhibitorBusinessID, ScanDate DESC)
    """))
    db.commit()


try:
    with SessionLocal() as _db:
        ensure_tables(_db)
except Exception as e:
    print(f"[event_leads] Table ensure warning: {e}")


# ── Resolve a badge code into attendee details ──────────────────────────────

def _resolve_badge(db: Session, event_id: int, badge_code: str) -> Optional[dict]:
    """Look up the badge code across the conference + simple registration tables.
    Returns a normalized {RegID, Name, Email, Phone, Business} or None."""
    if not badge_code:
        return None

    # Conference registrations have BadgeCode
    row = db.execute(text("""
        SELECT TOP 1 RegID, AttendeeFirstName, AttendeeLastName,
               AttendeeEmail, AttendeePhone, AttendeeBusinessName
          FROM OFNConferenceRegistrations
         WHERE EventID = :eid AND BadgeCode = :bc
    """), {"eid": event_id, "bc": badge_code}).fetchone()
    if row:
        first = row.AttendeeFirstName or ""
        last  = row.AttendeeLastName  or ""
        return {
            "RegID":     int(row.RegID),
            "Name":      f"{first} {last}".strip() or None,
            "Email":     row.AttendeeEmail,
            "Phone":     row.AttendeePhone,
            "Business":  getattr(row, "AttendeeBusinessName", None),
            "Source":    "conference",
        }

    # Fall back: simple/basic registration tables don't carry a badge code by
    # default, but some events may have used the RegID itself printed on the
    # nametag. Accept "REG-<id>" as a manual lookup.
    if badge_code.upper().startswith("REG-") and badge_code[4:].isdigit():
        rid = int(badge_code[4:])
        row = db.execute(text("""
            SELECT TOP 1 RegID, AttendeeFirstName, AttendeeLastName,
                   AttendeeEmail, AttendeePhone
              FROM OFNEventRegistrations
             WHERE EventID = :eid AND RegID = :rid
        """), {"eid": event_id, "rid": rid}).fetchone()
        if row:
            first = row.AttendeeFirstName or ""
            last  = row.AttendeeLastName  or ""
            return {
                "RegID":     int(row.RegID),
                "Name":      f"{first} {last}".strip() or None,
                "Email":     row.AttendeeEmail,
                "Phone":     row.AttendeePhone,
                "Business":  None,
                "Source":    "simple",
            }
    return None


@router.get("/api/events/{event_id}/leads/lookup")
def lookup_badge(event_id: int, code: str, db: Session = Depends(get_db)):
    """Pre-scan lookup so the UI can confirm the right person before logging."""
    res = _resolve_badge(db, event_id, code)
    if not res:
        raise HTTPException(status_code=404, detail=f"No registration matches badge '{code}'.")
    return res


# ── Scan endpoint — log a lead ──────────────────────────────────────────────

@router.post("/api/events/{event_id}/leads/scan")
def scan_lead(event_id: int, body: dict, db: Session = Depends(get_db)):
    """Body: {ExhibitorBusinessID, ScannedByPeopleID, BoothAppID?, BadgeCode?,
              AttendeeName?, AttendeeEmail?, AttendeePhone?, AttendeeBusiness?,
              Rating?, Interest?, Notes?, FollowUpStatus?}"""
    exhibitor_biz = body.get("ExhibitorBusinessID")
    scanner_pid   = body.get("ScannedByPeopleID")
    if not exhibitor_biz or not scanner_pid:
        raise HTTPException(400, "ExhibitorBusinessID and ScannedByPeopleID are required.")

    badge = body.get("BadgeCode")
    resolved = _resolve_badge(db, event_id, badge) if badge else None

    # Dedupe by (event, exhibitor, badge) within 5 minutes — guards against
    # accidental double-taps on a barcode reader.
    if badge:
        recent = db.execute(text("""
            SELECT TOP 1 ScanID FROM OFNEventLeadScan
             WHERE EventID = :eid AND ExhibitorBusinessID = :biz
               AND BadgeCode = :bc
               AND ScanDate >= DATEADD(minute, -5, GETDATE())
        """), {"eid": event_id, "biz": exhibitor_biz, "bc": badge}).fetchone()
        if recent:
            return {"ScanID": int(recent.ScanID), "deduped": True,
                    "message": "Already scanned in the last 5 minutes."}

    res = db.execute(text("""
        INSERT INTO OFNEventLeadScan
            (EventID, ExhibitorBusinessID, BoothAppID, ScannedByPeopleID,
             AttendeeRegID, AttendeeName, AttendeeEmail, AttendeePhone,
             AttendeeBusiness, BadgeCode, Rating, Interest, Notes,
             FollowUpStatus, FollowUpAt)
        OUTPUT INSERTED.ScanID
        VALUES (:eid, :biz, :booth, :pid, :rid, :nm, :em, :ph, :bz, :bc,
                :rt, :it, :nt, :fs, :fa)
    """), {
        "eid":   event_id,
        "biz":   int(exhibitor_biz),
        "booth": body.get("BoothAppID"),
        "pid":   int(scanner_pid),
        "rid":   resolved["RegID"] if resolved else None,
        "nm":    body.get("AttendeeName")     or (resolved or {}).get("Name"),
        "em":    body.get("AttendeeEmail")    or (resolved or {}).get("Email"),
        "ph":    body.get("AttendeePhone")    or (resolved or {}).get("Phone"),
        "bz":    body.get("AttendeeBusiness") or (resolved or {}).get("Business"),
        "bc":    badge,
        "rt":    body.get("Rating"),
        "it":    body.get("Interest"),
        "nt":    body.get("Notes"),
        "fs":    body.get("FollowUpStatus", "new"),
        "fa":    body.get("FollowUpAt"),
    }).fetchone()
    db.commit()
    return {"ScanID": int(res.ScanID), "deduped": False, "resolved": bool(resolved)}


# ── Read / list / update / delete ───────────────────────────────────────────

@router.get("/api/events/{event_id}/leads")
def list_my_leads(
    event_id: int,
    business_id: int = Query(..., description="Exhibitor business asking — scopes the result"),
    status: Optional[str] = Query(None),
    rating_min: Optional[int] = Query(None, ge=1, le=5),
    db: Session = Depends(get_db),
):
    """List the requesting exhibitor's lead scans for an event."""
    where = ["EventID = :eid", "ExhibitorBusinessID = :biz"]
    params = {"eid": event_id, "biz": business_id}
    if status:
        where.append("FollowUpStatus = :st"); params["st"] = status
    if rating_min is not None:
        where.append("Rating >= :rm");        params["rm"] = rating_min

    rows = db.execute(text(f"""
        SELECT ScanID, EventID, ExhibitorBusinessID, BoothAppID, ScannedByPeopleID,
               AttendeeRegID, AttendeeName, AttendeeEmail, AttendeePhone,
               AttendeeBusiness, BadgeCode, Rating, Interest, Notes,
               FollowUpStatus, FollowUpAt, ScanDate
          FROM OFNEventLeadScan
         WHERE {' AND '.join(where)}
         ORDER BY ScanDate DESC
    """), params).fetchall()
    return [dict(r._mapping) for r in rows]


@router.put("/api/events/leads/{scan_id}")
def update_lead(scan_id: int, body: dict, db: Session = Depends(get_db)):
    db.execute(text("""
        UPDATE OFNEventLeadScan SET
            AttendeeName=:nm, AttendeeEmail=:em, AttendeePhone=:ph,
            AttendeeBusiness=:bz,
            Rating=:rt, Interest=:it, Notes=:nt,
            FollowUpStatus=:fs, FollowUpAt=:fa, UpdatedDate=GETDATE()
        WHERE ScanID = :sid
    """), {
        "sid": scan_id,
        "nm":  body.get("AttendeeName"),
        "em":  body.get("AttendeeEmail"),
        "ph":  body.get("AttendeePhone"),
        "bz":  body.get("AttendeeBusiness"),
        "rt":  body.get("Rating"),
        "it":  body.get("Interest"),
        "nt":  body.get("Notes"),
        "fs":  body.get("FollowUpStatus", "new"),
        "fa":  body.get("FollowUpAt"),
    })
    db.commit()
    return {"ok": True}


@router.delete("/api/events/leads/{scan_id}")
def delete_lead(scan_id: int, db: Session = Depends(get_db)):
    db.execute(text("DELETE FROM OFNEventLeadScan WHERE ScanID = :sid"), {"sid": scan_id})
    db.commit()
    return {"ok": True}


# ── CSV export — drop into HubSpot / Salesforce / a spreadsheet ─────────────

@router.get("/api/events/{event_id}/leads/export.csv")
def export_leads_csv(event_id: int, business_id: int, db: Session = Depends(get_db)):
    rows = db.execute(text("""
        SELECT ScanID, ScanDate, AttendeeName, AttendeeBusiness, AttendeeEmail,
               AttendeePhone, BadgeCode, Rating, Interest, FollowUpStatus,
               FollowUpAt, Notes
          FROM OFNEventLeadScan
         WHERE EventID = :eid AND ExhibitorBusinessID = :biz
         ORDER BY ScanDate DESC
    """), {"eid": event_id, "biz": business_id}).fetchall()
    buf = io.StringIO()
    w = csv.writer(buf)
    headers = ["ScanID","ScanDate","Name","Business","Email","Phone",
               "BadgeCode","Rating","Interest","FollowUpStatus","FollowUpAt","Notes"]
    w.writerow(headers)
    for r in rows:
        d = dict(r._mapping)
        w.writerow([d.get(k.replace("Name","AttendeeName")
                          .replace("Business","AttendeeBusiness")
                          .replace("Email","AttendeeEmail")
                          .replace("Phone","AttendeePhone"), d.get(k))
                    if k in ("Name","Business","Email","Phone") else d.get(k)
                    for k in headers])
    buf.seek(0)
    return StreamingResponse(
        iter([buf.getvalue()]),
        media_type="text/csv",
        headers={"Content-Disposition": f'attachment; filename="event_{event_id}_leads.csv"'},
    )


@router.get("/api/events/{event_id}/leads/summary")
def leads_summary(event_id: int, business_id: int, db: Session = Depends(get_db)):
    """One-call dashboard: total, by status, by rating."""
    total = db.execute(text("""
        SELECT COUNT(1) AS n FROM OFNEventLeadScan
         WHERE EventID = :eid AND ExhibitorBusinessID = :biz
    """), {"eid": event_id, "biz": business_id}).fetchone()
    by_status = db.execute(text("""
        SELECT FollowUpStatus, COUNT(1) AS n FROM OFNEventLeadScan
         WHERE EventID = :eid AND ExhibitorBusinessID = :biz
         GROUP BY FollowUpStatus
    """), {"eid": event_id, "biz": business_id}).fetchall()
    by_rating = db.execute(text("""
        SELECT Rating, COUNT(1) AS n FROM OFNEventLeadScan
         WHERE EventID = :eid AND ExhibitorBusinessID = :biz AND Rating IS NOT NULL
         GROUP BY Rating
    """), {"eid": event_id, "biz": business_id}).fetchall()
    return {
        "event_id":     event_id,
        "business_id":  business_id,
        "total":        int(total.n) if total else 0,
        "by_status":    {r.FollowUpStatus: int(r.n) for r in by_status},
        "by_rating":    {int(r.Rating): int(r.n) for r in by_rating if r.Rating is not None},
    }
